import type { Knex } from 'knex';
import { getDefaultSitemapSettings } from '@/lib/sitemap-utils';

/**
 * Migration: Create Settings Table
 *
 * Creates the settings table with default values
 */

export async function up(knex: Knex): Promise<void> {
  // Create settings table
  await knex.schema.createTable('settings', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.string('key', 255).notNullable().unique();
    table.jsonb('value').notNullable();
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
  });

  // Create index
  await knex.schema.raw('CREATE INDEX IF NOT EXISTS idx_settings_key ON settings(key)');

  // Insert default settings (sitemap: Webwow-generated by default for new apps)
  await knex('settings').insert([
    { key: 'site_name', value: JSON.stringify('My Site') },
    { key: 'site_description', value: JSON.stringify('') },
    { key: 'webwow_version', value: JSON.stringify('0.1.0') },
    { key: 'sitemap', value: JSON.stringify(getDefaultSitemapSettings()) },
    { key: 'webwow_badge', value: JSON.stringify(false) },
    { key: 'timezone', value: JSON.stringify('UTC') },
  ]).onConflict('key').ignore();
}

export async function down(knex: Knex): Promise<void> {
  // Drop table
  await knex.schema.dropTableIfExists('settings');
}
